# Generated by Django 5.2.6 on 2025-09-30 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe comenzar con 2 (casa) o 9 (móvil) y tener 9 digitos.', regex='^[29]\\d{8}$')]),
        ),
    ]
